_target_: segment_anything.modeling.mask_decoder.MaskDecoder
num_multimask_outputs: 3
transformer:
  _target_: segment_anything.modeling.transformer.TwoWayTransformer
  depth: 2
  embedding_dim: ${ ...prompt_embed_dim }
  mlp_dim: 2048
  num_heads: 8
transformer_dim: ${ ..prompt_embed_dim }
iou_head_depth: 3
iou_head_hidden_dim: 256
