_target_: segment_anything.modeling.image_encoder.ImageEncoderViT
depth: 12
embed_dim: 768
img_size: ${ ..image_size }
mlp_ratio: 4
norm_layer:
  _partial_: true
  _target_: torch.nn.LayerNorm
  eps: 1e-6
num_heads: 12
patch_size: ${ ..vit_patch_size }
qkv_bias: True
use_rel_pos: True
global_attn_indexes: [ 2, 5, 8, 11 ]
window_size: 14
out_chans: ${ ..prompt_embed_dim }
