defaults:
  - prompt_encoder: sam
  - mask_decoder: sam
  - _self_

_target_: sam_pt.modeling.sam.SamHQHydra

checkpoint: ${hydra:runtime.cwd}/models/samhq_ckpts/sam_hq_vit_t.pth

prompt_embed_dim: 256
image_size: 1024
vit_patch_size: 16
image_embedding_size: 64

pixel_mean: [ 123.675, 116.28, 103.53 ]
pixel_std: [ 58.395, 57.12, 57.375 ]

image_encoder:
  _target_: segment_anything_hq.modeling.TinyViT
  img_size: ${..image_size}
  in_chans: 3
  num_classes: 1000
  embed_dims: [ 64, 128, 160, 320 ]
  depths: [ 2, 2, 6, 2 ]
  num_heads: [ 2, 4, 5, 10 ]
  window_sizes: [ 7, 7, 14, 7 ]
  mlp_ratio: 4.
  drop_rate: 0.
  drop_path_rate: 0.0
  use_checkpoint: False
  mbconv_expand_ratio: 4.0
  local_conv_size: 3
  layer_lr_decay: 0.8

prompt_encoder:
  _target_: segment_anything_hq.modeling.prompt_encoder.PromptEncoder

mask_decoder:
  _target_: segment_anything_hq.modeling.mask_decoder_hq.MaskDecoderHQ
  vit_dim: 160
